apiVersion: batch/v1
kind: CronJob
metadata:
  name: rabbitmq-publish
spec:
  schedule: "*/15 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rabbitmq-client
              image: ghcr.io/kedacore/rabbitmq-client:v1.0
              imagePullPolicy: Always
              env:
                - name: RABBITMQ_CONNECTION_STRING
                  valueFrom:
                    secretKeyRef:
                      name: mycluster-rabbitmq-default-user
                      key: connection_string
              command:
                [
                  "send",
                  "$(RABBITMQ_CONNECTION_STRING)",
                  "100",
                ]
          restartPolicy: Never
      backoffLimit: 4
