# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: ubuntu
    plan: pico
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done

  - name: backup
    plan: nano
    image: alpine:3
    command:
      - "sh"
      - "-euc"
      - |
        apk update
        apk add --no-cache aws-cli
        apk add --no-cache mongodb-tools
        sleep infinity
    envVarsFrom:
      secrets:
        - name: kanban-blueprint-backup-creds
        - name: wekan-psmdb-secrets-system

  # - name: recover
  #   plan: nano
  #   image: alpine:3
  #   command:
  #     - "sh"
  #     - "-euc"
  #     - |
  #       apk update
  #       apk add --no-cache aws-cli
  #       apk add --no-cache mongodb-tools
  #       sleep infinity
  #   envVarsFrom:
  #     secrets:
  #       - name: kanban-blueprint-recovery-creds
  #       - name: wekan-psmdb-secrets-system

  - name: wekan
    plan: micro
    port: 8080
    ingress:
      enabled: true
    image: ghcr.io/wekan/wekan:v8.23
    mountVolumes:
      - name: wekan-files
        path: /dados
        ownership: "999:999"
    envVars:
      WRITABLE_PATH: "/dados"
      ROOT_URL: "https://kanban-wekan.global.dev.lwsa-idp-testbed.ingress.sh"
    envVarsFrom:
      dbServers:
        - name: wekan
          type: psmdb
          mappings:
            MONGO_URL: MONGODB_URI

dbServers:
  - name: wekan
    type: psmdb
    version: "7.0"
    plan: micro
    size: 100Gi
    replicas: 1
    pause: false
    expose:
      enabled: true
      sourceRanges:
        - "189.0.0.0/8"
        - "186.0.0.0/8"
        - "187.0.0.0/8"
        - "185.0.0.0/8"
        - "177.0.0.0/8"
        - "179.0.0.0/8"
        - "191.0.0.0/8"
        - "70.0.0.0/8"

  - name: wekan-d
    type: psmdb
    plan: small
    version: "7.0"
    size: 50Gi
    replicas: 3
    expose:
      enabled: true
    restoreFrom:
      name: wekan

volumes:
  - name: wekan-files
    size: 100Gi