# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: ubuntu
    plan: nano
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done

  # - name: wekan
  #   plan: micro
  #   port: 8080
  #   ingress:
  #     enabled: true
  #   image: wekanteam/wekan:v7.72
  #   mountVolumes:
  #     - name: wekan-files
  #       path: /dados
  #   envVars:
  #     WRITABLE_PATH: "/dados"
  #     ROOT_URL: "https://kanban-wekan.global.prod.demo.ingress.sh"
  #   envVarsFrom:
  #     dbServers:
  #       - name: wekan-banco
  #         type: psmdb
  #         mappings:
  #           MONGO_URL: MONGODB_URI

dbServers:
  - name: wekan
    type: psmdb
    plan: small
    size: 100Gi
    replicas: 1
    pause: false
    expose:
      enabled: true
      sourceRanges:
        - "189.0.0.0/8"
        - "186.0.0.0/8"
        - "187.0.0.0/8"
        - "185.0.0.0/8"
        - "177.0.0.0/8"
        - "179.0.0.0/8"
        - "191.0.0.0/8"
        - "70.0.0.0/8"

  # - name: wekan-copy
  #   type: psmdb
  #   plan: small
  #   size: 50Gi
  #   replicas: 3
  #   expose:
  #     enabled: true
    # restoreFrom:
    #   name: wekan

# volumes:
#   - name: wekan-files
#     size: 100Gi