# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: ubuntu
    plan: pico
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done

  - name: alpine
    plan: nano
    image: alpine:3
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done
    envVarsFrom:
      secrets:
        - name: kanban-blueprint-backup-creds
        - name: wekan-psmdb-secrets-system

  - name: wekan
    plan: micro
    port: 8080
    ingress:
      enabled: true
    image: ghcr.io/wekan/wekan:v7.85
    mountVolumes:
      - name: wekan-files
        path: /dados
        ownership: "999:999"
    envVars:
      WRITABLE_PATH: "/dados"
      ROOT_URL: "https://kanban-wekan.global.prod.demo.ingress.sh"
    envVarsFrom:
      dbServers:
        - name: wekan
          type: psmdb
          mappings:
            MONGO_URL: MONGODB_URI

dbServers:
  - name: wekan
    type: psmdb
    plan: micro
    size: 100Gi
    replicas: 1
    pause: false
    expose:
      enabled: true
      sourceRanges:
        - "189.0.0.0/8"
        - "186.0.0.0/8"
        - "187.0.0.0/8"
        - "185.0.0.0/8"
        - "177.0.0.0/8"
        - "179.0.0.0/8"
        - "191.0.0.0/8"
        - "70.0.0.0/8"

  # - name: wekan-copy
  #   type: psmdb
  #   plan: small
  #   size: 50Gi
  #   replicas: 3
  #   expose:
  #     enabled: true
    # restoreFrom:
    #   name: wekan

volumes:
  - name: wekan-files
    size: 100Gi