apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: production-ready
spec:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  replicas: 3
  resources:
    requests:
      cpu: 75m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  persistence:
    storageClassName: {{ $.Values.global.dbStorageClassName }}
    storage: "50Gi"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - production-ready
        topologyKey: kubernetes.io/hostname
  override:
    service:
      spec:
        loadBalancerSourceRanges:
          - "189.0.0.0/8"
          - "186.0.0.0/8"
          - "187.0.0.0/8"
          - "201.0.0.0/8"
          - "70.0.0.0/8"
