# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-idp/static/main/schemas/blueprint.json

services:
  - name: gitea
    image: docker.io/gitea/gitea:1.23.4
    plan: micro
    port: 3000
    ingress:
      enabled: true
    additionalPorts:
      - port: 22
        expose:
          enabled: true
    mountVolumes:
      - name: data
        path: /data
    envVars:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: "db-rw:5432"
      GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: "true"
      GITEA__server__SSH_DOMAIN: "191.252.224.48.nip.io"
    envVarsFrom:
      dbServers:
        - name: db
          type: cnpg
          mappings:
            GITEA__database__NAME: DB_NAME
            GITEA__database__USER: DB_USER
            GITEA__database__PASSWD: DB_PASSWORD

  # - name: act-runner
  #   image: docker.io/gitea/act_runner:0.2.11
  #   plan: micro
  #   envVars:
  #     GITEA_INSTANCE_URL: http://gitea
  #     GITEA_RUNNER_LABELS: "ubuntu-latest:host,ubuntu-22.04:host,ubuntu-20.04:host"
  #   mountVolumes:
  #     - name: act-data
  #       path: /data
  #   envVarsFrom:
  #     secrets:
  #       - name: token

secrets:
  - name: token
    namespace: forge
    data:
      # configurar a posteriori após criar gitea, pegar em Admin Settings, Runners, Create new runner, copiar Registration token e criprografar com Sealed Secrets
      GITEA_RUNNER_REGISTRATION_TOKEN: AgAVfUAlYcg5C/jN9iq33Wx8wrcvhdds65O9qHeb4rHOEDSeUc97Ek9ZsHiS8vV9OyNhBKD2r2OaOr2clGlIa3qDwB2nMLigJMRDK2D+3iAc9KgAQzLkTXl2ZTla49+YxtCrv8khyRqcifl2J72qOOx6vCDpntailE88Tnm6ikOx4zVgskFY3cCMIXYXSvu4Jp6XrGvwjKvVgQiJNmdUclHOxqpJwwmutSiUg8gCQAd2QVUbk6bN2RHsEYyjXUUFwT0vkX1ceDcnxTg75OVOoNpg1mopFGWwnA/PfobKX2LiIusm6JxmGldTzfLsGoBx+2qxPFMflrcZ1DeHL62wlctS5smMEdmbfC6TFCSnqjxTtluANuCl/izmXnNm+562pw0E4MgJJxQ2aZY5lcg8ZWZiUkxATUH6fzwR3zGoSexTvci/PBH4BqdObetboM5uVJpk19N1c5lU2//+A+u9aiHBzNuzM3KcLDyp+yXkXqhsSf9gyWWJCaS5aywUWUo+rhpP6BKE8Udk5PjiM+zFCR/mH0OQc16N6ADe8cHwyqP7NygRmprJG6NZyACX7b8firv8lODs/2NOWKzOMMmWSCvVyLbf/RinvRHgI/I4KRSNU36L70xOP1RGuJ5FIFT4bOCJTHgt4lmqt4u9hdbfzbndsgKkDNRAeeB1WZikacqga0pqRJ0DxKnEqi+naPgfDOSjZG745298cDTgxsyQIqRC4PF3NkfV2BP2phBFMwK5K4LtOg8nRBcm

dbServers:
  - name: db
    type: cnpg
    plan: micro
    size: 50Gi
    version: "17"

volumes:
  - name: data
    size: 50Gi
  - name: act-runner-vol
    size: 50Gi