# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: nextcloud
    plan: nano
    port: 80
    ingress:
      enabled: true
    image: nextcloud:29.0.8
    mountVolumes:
      - name: nextcloud-vol
        path: /var/www/html
    envVarsFrom:
      dbServers:
        - name: nextcloud-db
          type: cnpg
          mappings:
            POSTGRES_HOST: DB_HOST
            POSTGRES_READ: DB_HOST_READ
            POSTGRES_USER: DB_USER
            POSTGRES_PASSWORD: DB_PASSWORD
            POSTGRES_DB: DB_NAME
            CONNECTION_STRING: DATABASE_URL
        - name: redis
          type: dragonfly
          mappings:
            REDIS_HOST_PASSWORD: REDIS_PASSWORD

  - name: ubuntu
    plan: pico
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done

dbServers:
  - name: nextcloud-db
    type: cnpg
    version: "15"
    plan: micro
    size: 50Gi
    # Default 1 replica. Para prod usar sempre 3
    # replicas: 3

  - name: redis
    type: dragonfly
    plan: micro
    passwordAuth:
      enabled: true
    # Default 1 replica. Para prod usar ao menos 2
    # replicas: 2

volumes:
  - name: nextcloud-vol
    size: 50Gi