# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: teste
    image: cilium/echoserver
    plan: nano
    ingress:
      enabled: true