# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: n8n
    image: giba/giba
    plan: micro
    port: 80
    additionalPorts:
      - port: 90
        expose:
          enabled: false
    egress:
      enabled: true
      toCIDRs:
        - range: 0.0.0.0/8
        - range: 5.5.5.5/5
      toFQDNs:
        - host: www.locaweb.com.br
        - pattern: *.locaweb.com.br
          port: 80
          protocol: UDP
        
    command:
      - a
      - b
    args:
      - c
    ingress:
      enabled: true
    mountVolumes:
      - name: dados
        path: dados
        ownership: 100:100
    envVars:
      a: b
      c: "3"
    envVarsFrom:
      searches:
        - name: nome10
          type: elasticsearch
      configMaps:
        - name: mapa4
          mappings:
            r: t
      messageBrokers:
        - name: mycluster
          type: rabbitmq
          mappings:
            d: e
      dbServers:
        - name: a
          type: dragonfly
          mappings:
            e: k
        - name: nome4
          type: cnpg
          mappings:
            e: f
      secrets:
        - name: segredo1
    allowTo:
      services:
        - namespace: a
          name: b
        - namespace: c
          name: c
    minReplicas: 0
    maxReplicas: 10
    scaleTriggers:
      - type: cpu
        metadata:
          a: b

  - name: consumer
    image: keda/keda
    plan: small
    scaleTriggers:
      - type: d
        metadata:
          d: e

configmaps:
  - name: asd
    data:
      e: r

searches:
  - name: nome
    type: elasticsearch
    version: "10"
    nodes:
      master:
        replicas: 3
        plan: "4xlarge"
        size: 30Gi
      data:
        replicas: 3
        plan: pico
        size: 4Gi
    dashboard:
      enabled: true
      replicas: 1
      plan: nano

jobs:
  - name: nome
    image: imagem
    plan: medium
    hook: PostSync
    command:
      - a
      - d
    envVarsFrom:
      messageBrokers:
        - name: a
          type: rabbitmq
          mappings:
            r: t
      dbServers:
        - name: s
          type: ferretdb
          mappings:
            d: e
        - name: d
          type: psmdb
          mappings:
            e: r
      secrets:
        - name: d
          mappings:
            a: d

cronjobs:
  - name: publisher
    image: imager/image
    plan: micro
    schedule: '*/10 * * * *'
    command:
      - a
      - b
    args:
      - d
    envVarsFrom:
      messageBrokers:
        - name: mycluster10
          type: rabbitmq

secrets:
  - name: segredo1
    namespace: nome
    data:
      df: df
      

messageBrokers:
  - name: a
    type: rabbitmq
    plan: "4xlarge"
    size: 3Gi
    replicas: 3
    expose:
      enabled: true
      sourceRanges:
        - 0.0.0.0/0


dbServers:
  - name: doc4
    type: ferretdb
    plan: medium
    version: "10"
    size: 40Gi
    expose:
      enabled: true
      sourceRanges:
        - 0.0.0.0/0
    pause: false
    restoreFrom:
      name: a

  - name: db
    type: cnpg
    plan: nano
    version: "30"
    size: 10Gi
    pause: true
    expose:
      enabled: false
      sourceRanges:
        - 0.0.0.0/8
  - name: wekan5
    type: psmdb
    plan: micro
    size: 10Gi
    version: "10"
    pause: false
    expose:
      enabled: true
      sourceRanges:
        - 0.0.0.0/2
    replicas: 3

  - name: redis10
    type: dragonfly
    plan: medium
    memcached:
      enabled: false
    passwordAuth:
      enabled: true
    snapshot:
      enabled: true
      size: 10Gi

  - name: banco3
    type: pxc
    plan: nano
    version: "8.0"
    size: 45Gi
    replicas: 3

volumes:
  - name: n8n
    size: 50Gi
  - name: nome2
    size: 45Gi
