# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: n8n
    image: n8nio/n8n
    plan: nano
    port: 5678
    command:
      - /bin/sh
    args:
      - -c
      - sleep 5; n8n start
    ingress:
      enabled: true
    mountVolumes:
      - name: n8n
        path: /home/node/.n8n
        # usar parâmetro abaixo quando containers exigirem mudar ownership do volume anexado
        ownership: "1000:1000"
    envVars:
      DB_TYPE: postgresdb
      N8N_EDITOR_BASE_URL: "https://agent-n8n.global.dev.lwsa-idp-testbed.ingress.sh"
    envVarsFrom:
      dbServers:
        - name: db
          type: cnpg
          mappings:
            DB_POSTGRESDB_HOST: DB_HOST
            DB_POSTGRESDB_DATABASE: DB_NAME
            DB_POSTGRESDB_USER: DB_USER
            DB_POSTGRESDB_PASSWORD: DB_PASSWORD

dbServers:
  - name: db
    type: cnpg
    plan: nano
    size: 50Gi
    version: "16"

volumes:
  - name: n8n
    size: 50Gi