opentelemetry-demo:

  # https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/examples/bring-your-own-observability/values.yaml
  default:
    envOverrides:
      - name: OTEL_COLLECTOR_NAME
        value: k8s-monitoring-alloy-receiver.monitoring

  opentelemetry-collector:
    enabled: false

  jaeger:
    enabled: false

  prometheus:
    enabled: false

  grafana:
    enabled: false
