services:
  - name: ubuntu
    plan: nano
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done

  # - name: wekan
  #   plan: micro
  #   port: 8080
  #   ingress:
  #     enabled: true
  #   image: wekanteam/wekan:v7.72
  #   mountVolumes:
  #     - name: wekan-files
  #       path: /dados
  #   envVars:
  #     WRITABLE_PATH: "/dados"
  #     ROOT_URL: "https://kanban-wekan.global.prod.demo.ingress.sh"
  #   envVarsFrom:
  #     dbServers:
  #       - name: wekan-banco
  #         type: psmdb
  #         mappings:
  #           MONGO_URL: MONGODB_URI

dbServers: # Optional. If defined, should contain one or more entries
  - name: wekan # mandatory
    type: psmdb # mandatory. Value should be one of: pxc, cnpg, dragonfly, psmdb, ferretdb
    plan: small # mandatory
    size: 100Gi # mandatory
    replicas: 1 # optional. If defined, integer
    pause: false # optional, boolean
    expose: # optional
      enabled: true # mandatory, bollean
      sourceRanges: # optional, list of strings in CIDR format
        - "189.0.0.0/8"
        - "186.0.0.0/8"
        - "187.0.0.0/8"
        - "185.0.0.0/8"
        - "177.0.0.0/8"
        - "179.0.0.0/8"
        - "191.0.0.0/8"

  - name: wekan-2
    type: psmdb
    plan: small
    size: 100Gi
    # restoreFrom:
    #   name: wekan
    expose:
      enabled: true
      sourceRanges:
        - "189.0.0.0/8"
        - "186.0.0.0/8"
        - "187.0.0.0/8"
        - "185.0.0.0/8"
        - "177.0.0.0/8"
        - "179.0.0.0/8"

# volumes:
#   - name: wekan-files
#     size: 100Gi