# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

configmaps:
  - name: mapa
    data:
      nome: Giba
      empresa: Locaweb
  
  - name: pasta
    data:
      arq1.txt: |
        linha 1
        linha 2
        linha 3
      arq2.txt: |
        linha 4
        linha 5
        linha 6
      arq3.txt: |
        linha 7
        linha 8
        linha 9

  - name: outromapa
    data:
      foo: bar

cronjobs:
  - name: test-cron
    image: ubuntu
    plan: pico
    schedule: "*/5 * * * * "
    mountConfigMaps:
      - name: pasta
        path: /etc/config
    command:
      - /bin/sh
      - "-c"
      - |
        export DEBIAN_FRONTEND=noninteractive
        timeout --foreground 180s \
          apt-get update \
          && apt-get install -y curl \
          || { echo "apt-get failed"; exit 1; }
        echo "Teste $a" # imprimir "Teste b"
        curl --max-time 10 http://wp.portal
        cat /etc/config/arq3.txt
    allowTo:
      services:
        - namespace: portal
          name: wp
    egress:
      enabled: true
      toFQDNs:
        - pattern: '*.ubuntu.com'
    envVarsFrom:
      dbServers:
        - name: pg
          type: cnpg
    envVars:
      a: b

jobs:
  - name: a-job
    image: ubuntu
    plan: pico
    envVars:
      FOO: bar
    envVarsFrom:
      secrets:
        - name: segredo
          mappings:
            VALOR: chave
      configMaps:
        - name: mapa
          mappings:
            NAME: nome
      searches:
        - name: mysearch
          type: elasticsearch
      dbServers:
        - name: pg
          type: cnpg
    mountVolumes:
      - name: test-vol
        path: /data
    mountConfigMaps:
      - name: pasta
        path: /etc/config
    command:
      - "/bin/sh"
    args:
      - "-c"
      - |
        echo "VALOR=$VALOR"
        echo "chave=$chave"
        echo "NAME=$NAME"
        echo "nome=$nome"
        echo "ELASTICSEARCH_HOST=$ELASTICSEARCH_HOST"
        echo "DATABASE_URL=$DATABASE_URL"
        echo "Current time:"
        date
        echo "Appending time to log..."
        date >> /data/log.txt
        echo "Contents of /data/log.txt:"
        cat /data/log.txt
        cat /etc/config/arq2.txt
      
volumes:
  - name: test-vol
    size: 10Gi

services:
  - name: python-web-app
    plan: pico
    image: forge-gitea.global.dev.lwsa-idp-testbed.ingress.sh/giba/python-web-app:1.0.0
    ingress:
      enabled: true

  - name: pg-bench
    plan: micro
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done
    envVarsFrom:
      dbServers:
        - name: pg
          type: cnpg

  - name: console
    plan: micro
    image: ubuntu
    replicas: 2
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done
    mountConfigMaps:
      - name: pasta
        path: /etc/config
    egress:
      enabled: true
      toCIDRs:
        - range: 1.1.1.1/32
          port: 53
          protocol: UDP
      toFQDNs:
        # na ausência de port/protocol, conexões para qualquer porta e protocolo são permitidas
        - pattern: '*.ubuntu.com'
        - pattern: '*.amazonaws.com'
        - host: 'poc.object-storage.sh'
        - host: 'downloads.mongodb.com'
          port: 443
          protocol: TCP
    envVarsFrom:
      secrets:
        - name: segredo
          mappings:
            CHAVE: chave
      configMaps:
        - name: mapa
          mappings:
            NAME: nome
            COMPANY: empresa
        # na ausência de mappings, chaves do segredo são mapeadas diretamente para nomes das variáveis de ambiente
        - name: outromapa
      searches:
        - name: mysearch
          type: elasticsearch
          mappings:
            ES_HOST: ELASTICSEARCH_HOST
            ES_PORT: ELASTICSEARCH_PORT
            ES_USER: ELASTICSEARCH_USER
            ES_PASSWORD: ELASTICSEARCH_PASSWORD
            ES_URI: ELASTICSEARCH_URL
      dbServers:
        - name: pg
          type: cnpg

  - name: echo
    plan: pico
    # porta onde o container ouve, default 10000
    port: 3000
    # usar expose no lugar de ingress se desejar expor via IP público diretamente.
    # neste caso não suporta emissão automática de certificados
    expose:
      enabled: true
      sourceRanges:
        - "189.0.0.0/8"
        - "186.0.0.0/8"
        - "187.0.0.0/8"
        - "70.0.0.0/8"
        - "177.0.0.0/8"
    # ingress:
    #   hosts:
    #     - echo.giba.tech
    #   enabled: true
    #   sourceRanges:
    #     - "189.0.0.0/8"
    #     - "186.0.0.0/8"
    #     - "187.0.0.0/8"
    image: cilium/echoserver

  - name: pgadmin
    ingress:
      enabled: true
    image: dpage/pgadmin4:9
    plan: micro
    envVars:
      PGADMIN_DEFAULT_EMAIL: gilberto.mautner@locaweb.com.br
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: "10000"
  
  - name: sysbench
    image: perconalab/sysbench:latest 
    plan: medium
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done
    envVarsFrom:
      dbServers:
        - name: newdb
          type: pxc

  - name: sysbench-cnpg
    image: perconalab/sysbench:latest 
    plan: medium
    command:
      - /bin/sh
      - -c
      - while :; do sleep 86400; done
    envVarsFrom:
      dbServers:
        - name: pg
          type: cnpg

secrets:
  - name: segredo
    namespace: utilities
    data:
      # Conteúdo do segredo deve ser criptografado via kubeseal
      chave: AgCX/Tmq60KW5xSvPcAyjy1KBIhEYbJ34TQvcT8RPotiC4m9NrtDwa5AVExCSMUMQRj4i76hIpwNNVdARSgoh+9JrwhjyKJT60NYlfoOs1lfqFDFIEt+XNZgEf7jNmpIJ2wHwYhci3vnF8cIKB8aktVQ8s5Vvlfq/y2poC02etMT8w11uToVYTfuk0LgRG2P3o+fYKLfnVE3+5mU/FdzVEYCeTRxLV0G4w6zA63dXr+iGwRgXaDpbSw/eokwMKMZRTYx9AFMpKV8an3i9Qa/fHgifyscwf3kNpbnSkrWVRQqBWskU4wysEDbzY63vXDHGGT//04sjAwgZnqON7WeAwRUKbrNQ9D/ervbAbYwOJ/cCkKmN9akv/zRttniHWo3a3Y4QBUY0iwSnErkz29yFKXZ/V/Gf9S1NTU+tCaiIczgKyg5ag8Oa4UfJ6h8VYd9YBp/BxNqrO8Qs5crU9tbl71s6cK0fhKDegn0bEFbKT+ZOAgHoO7dWC4v71xLHlLEN9dg/QjmZ8JuHZP9WfErxG5Ze519tMA5810Sa2gatIeLXxyHURF77vdHIqu2GcajnIX1fhHGXwQx/i7JTmqSLlXFL37dmC2lO2bjJmexrrpe6uUGYKoxb8hEf/2jZGo91EszNCJTAUVcnEFnmnoC8LsqIbfv9g4E7VDEkvGZ2Ff+4NO3b6UPtv0wCim9055Mse7+zqmbCAkH6fc=

dbServers:
  - name: mydb
    replicas: 1
    type: pxc
    version: "8.0"
    plan: small
    size: 200Gi
    expose:
      enabled: true
    # quando true, desliga banco, sem apagar dados. Serve para economizar recursos quando não precisa
    pause: false

  - name: testpxc
    type: pxc
    plan: small
    size: 20Gi
    version: "8.0"
    
  # - name: mydb-copy-2
  #   replicas: 1
  #   type: pxc
  #   version: "8.0"
  #   plan: large
  #   size: 200Gi
  #   restoreFrom:
  #     name: mydb

  # usado para teste de carga (sysbench) com base de 130 GB. Escalar para 3 replicas e 2xlarge para testar.
  - name: newdb
    replicas: 1
    type: pxc
    version: "8.0"
    plan: small
    size: 600Gi
    expose:
      enabled: true

  # usado para teste de carga (sysbench) com base de 40 GB
  - name: pg
    type: cnpg
    version: "16"
    plan: xlarge
    extensions:
      - vector
    size: 300Gi
    expose:
      enabled: true
    pause: false
    replicas: 3
    parameters:
      max_connections: "200"
  
  # - name: pg-copy
  #   type: cnpg
  #   version: "16"
  #   plan: micro
  #   size: 90Gi
  #   restoreFrom:
  #     name: pg

searches:
  - name: mysearch
    type: elasticsearch
    version: "8.19.9"
    expose:
      enabled: true
      sourceRanges:
        - "189.0.0.0/8"
        - "186.0.0.0/8"
        - "187.0.0.0/8"
        - "201.0.0.0/8"
        - "70.0.0.0/8"
    nodes:
      master:
        replicas: 3 # default 3
        plan: medium
        size: 80Gi
      data:
        replicas: 3 # default 3
        plan: large
        size: 160Gi
    dashboard:
      enabled: true
      sourceRanges:
        - "0.0.0.0/0"
        - "186.0.0.0/8"
        - "187.0.0.0/8"
        - "201.0.0.0/8"
        - "177.0.0.0/8"
        - "70.0.0.0/8"
      replicas: 1 # default 1
      plan: small

  - name: busca
    type: elasticsearch
    version: "9.2.0"
    nodes:
      master:
        replicas: 3
        plan: medium
        size: 80Gi
      data:
        replicas: 3
        plan: medium
        size: 80Gi
    dashboard:
      enabled: true
      replicas: 1
      plan: small