# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: consumer
    image: ghcr.io/kedacore/rabbitmq-client:v1.0
    plan: pico
    envVarsFrom:
      messageBrokers:
        - name: mycluster
          type: rabbitmq
    command:
      - receive
    args:
      - $(RABBITMQ_URL)
    # Ref https://keda.sh/docs/2.16/scalers/
    scaleTriggers:
      - type: rabbitmq
        metadata:
          hostFromEnv: RABBITMQ_URL
          queueName: hello
          queueLength: "5"

messageBrokers:
  - name: mycluster
    type: rabbitmq
    plan: micro
    size: 10Gi
    replicas: 3
    expose:
      enabled: true
      sourceRanges:
        - 189.0.0.0/8
