# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: consumer
    image: ghcr.io/kedacore/rabbitmq-client:v1.0
    plan: nano
    envVarsFrom:
      messageBrokers:
        - name: mycluster
          type: rabbitmq
    command:
      - receive
    args:
      - "amqp://default_user_lcGb0-ccU3zDVUI5pbs:CT3pVw_O_x9VOdavTsWEpthdeuJXoRVL@mycluster-rabbitmq.broker.svc:5672"

messageBrokers:
  - name: mycluster
    type: rabbitmq
    plan: micro
    size: 10Gi
    replicas: 3
    expose:
      enabled: true
      sourceRanges:
        - 189.0.0.0/8
