# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: consumer
    image: ghcr.io/kedacore/rabbitmq-client:v1.0
    plan: nano
    envVarsFrom:
      messageBrokers:
        - name: mycluster
          type: rabbitmq
    command:
      - sleep 1576800000

messageBrokers:
  - name: mycluster
    type: rabbitmq
    plan: micro
    size: 10Gi
    replicas: 3
    expose:
      enabled: true
