# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: consumer
    image: ghcr.io/kedacore/rabbitmq-client:v1.0
    plan: pico
    envVarsFrom:
      messageBrokers:
        - name: mycluster
          type: rabbitmq
    command:
      - receive
    args:
      - $(RABBITMQ_URL)
    autoscaling:
      enabled: true
      # Ref https://keda.sh/docs/2.16/scalers/
      triggers:
        - type: rabbitmq
          metadata:
            hostFromEnv: RABBITMQ_URL
            queueName: hello
            queueLength: "5"

cronjobs:
  - name: publish
    image: ghcr.io/kedacore/rabbitmq-client:v1.0
    plan: pico
    # Cooldown default é de 5 minutos, por isso espaçamos a cada 10 para garantir tempo necessário
    schedule: "*/10 * * * *"
    envVarsFrom:
      messageBrokers:
        - name: mycluster
          type: rabbitmq
    command:
      - "send"
      - "$(RABBITMQ_URL)"
      - "100"

messageBrokers:
  - name: mycluster
    type: rabbitmq
    plan: nano
    size: 10Gi
    replicas: 3
    expose:
      enabled: true
      sourceRanges:
        - 189.0.0.0/8
