# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: python-web-app
    image: gitea.platform.lwsa.tech/gilbertomautner1971/python-web-app:sha-6328727
    plan: pico
    ingress:
      enabled: true    