# yaml-language-server: $schema=https://raw.githubusercontent.com/lwsa-tech/platform-static/main/schemas/blueprint.json

services:
  - name: python-web-app
    image: registry.gitlab.platform.lwsa.tech/labs/python-web-app:latest
    plan: pico
    ingress:
      enabled: true

  - name: flask-todo
    image: registry.gitlab.platform.lwsa.tech/labs/flask-todo
    plan: pico
    ingress:
      enabled: true
    autoInstrumentation:
      enabled: true
    envVarsFrom:
      dbServers:
        - name: flask-todo
          type: cnpg
  
  - name: echo
    image: cilium/echoserver
    plan: pico
    ingress:
      enabled: true

  - name: echo2
    image: cilium/echoserver
    plan: pico
    ingress:
      enabled: true
      hosts:
        - echo2.giba.tech
  
  - name: echo3
    image: cilium/echoserver
    plan: pico
    expose:
      enabled: true
      sourceRanges:
        - "70.107.169.90/32"

jobs:
  - name: migrate-flask-todo
    image: registry.gitlab.platform.lwsa.tech/labs/flask-todo
    plan: pico
    # https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/
    hook: PostSync
    command: ["flask", "db", "upgrade"]
    envVarsFrom:
      dbServers:
        - name: flask-todo
          type: cnpg
  
dbServers:
  - name: flask-todo
    type: cnpg
    plan: nano
    version: "17"
    size: 10Gi